import { useState, useRef } from 'react';
import { useCompanyProfile } from '../context/CompanyContext';
import { useTheme } from '../context/ThemeContext';
import styles from '../styles/CompanySettings.module.css';

export default function CompanySettings({ isModal = false, onClose = null }) {
    const {
        companyName,
        website: storedWebsite,
        logo: storedLogo,
        logoOriginal,
        logoWhite,
        updateProfile,
        processLogoFile,
        clearProfile
    } = useCompanyProfile();
    const { theme } = useTheme();

    const [name, setName] = useState(companyName || 'Alshaya Enterprises');
    const [website, setWebsite] = useState(storedWebsite || 'https://alshayaenterprises.com/');
    const [logo, setLogo] = useState(storedLogo || {
        base64: logoOriginal || '',
        width: 1561,
        height: 865,
        isLight: false,
        whiteLogo: logoWhite || ''
    });
    const [error, setError] = useState(null);
    const [success, setSuccess] = useState(null);
    const [isProcessing, setIsProcessing] = useState(false);
    const fileInputRef = useRef(null);

    // Sync from context when it loads
    useEffect(() => {
        if (companyName) setName(companyName);
        if (storedWebsite) setWebsite(storedWebsite);
        if (storedLogo) setLogo(storedLogo);
    }, [companyName, storedWebsite, storedLogo]);

    const handleLogoUpload = async (e, type = 'original') => {
        const file = e.target.files?.[0];
        if (!file) return;

        setError(null);
        setIsProcessing(true);

        try {
            const logoData = await processLogoFile(file);
            
            // If we're updating a specific part of the logo
            setLogo(prev => {
                const current = prev || storedLogo || {};
                if (type === 'white') {
                    return {
                        ...current,
                        whiteLogo: logoData.base64,
                        // If there's no original yet, use this as both (fallback)
                        base64: current.base64 || logoData.base64,
                        width: current.width || logoData.width,
                        height: current.height || logoData.height
                    };
                } else {
                    return {
                        ...current,
                        base64: logoData.base64,
                        // If no white logo yet, use the one auto-generated by processLogoFile
                        whiteLogo: current.whiteLogo || logoData.whiteLogo,
                        width: logoData.width,
                        height: logoData.height,
                        isLight: logoData.isLight
                    };
                }
            });
            
            setSuccess(`${type === 'white' ? 'White' : 'Colored'} logo uploaded!`);
            setTimeout(() => setSuccess(null), 3000);
        } catch (err) {
            setError(err.message);
        } finally {
            setIsProcessing(false);
        }
    };

    const handleRemoveLogo = (type = 'both') => {
        if (type === 'both') {
            setLogo(null);
        } else if (type === 'white') {
            setLogo(prev => ({ ...prev, whiteLogo: null }));
        } else {
            setLogo(prev => ({ ...prev, base64: null }));
        }
        
        if (fileInputRef.current) {
            fileInputRef.current.value = '';
        }
    };

    const handleSave = () => {
        if (!name.trim()) {
            setError('Please enter a company name.');
            return;
        }

        setError(null);
        const result = updateProfile(name.trim(), logo, website.trim());

        if (result.success) {
            setSuccess('Company profile saved successfully!');
            setTimeout(() => {
                setSuccess(null);
                if (onClose) onClose();
            }, 1500);
        } else {
            setError(result.error);
        }
    };

    const handleReset = () => {
        if (window.confirm('Are you sure you want to reset your company profile? This cannot be undone.')) {
            clearProfile();
            setName('');
            setWebsite('');
            setLogo(null);
        }
    };

    const handleSkip = () => {
        updateProfile(name.trim() || 'Alshaya Enterprises', logo, website.trim() || 'https://alshayaenterprises.com/');
        if (onClose) onClose();
    };

    return (
        <div className={isModal ? styles.modalOverlay : styles.settingsPage}>
            <div className={isModal ? styles.modalContent : styles.settingsContainer}>
                {/* Header */}
                <div className={styles.header}>
                    <h2 className={styles.title}>
                        {isModal ? 'Welcome to BOQ FLOW' : 'Company Settings'}
                    </h2>
                    {isModal && (
                        <p className={styles.subtitle}>
                            Set up your company profile to personalize your documents
                        </p>
                    )}
                </div>

                {/* Form */}
                <div className={styles.form}>
                    {/* Company Name */}
                    <div className={styles.field}>
                        <label className={styles.label}>Company Name</label>
                        <input
                            type="text"
                            className={styles.input}
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            placeholder="Enter your company name"
                            maxLength={100}
                        />
                    </div>

                    {/* Company Website */}
                    <div className={styles.field}>
                        <label className={styles.label}>Company Website</label>
                        <input
                            type="text"
                            className={styles.input}
                            value={website}
                            onChange={(e) => setWebsite(e.target.value)}
                            placeholder="e.g. www.yourcompany.com"
                            maxLength={100}
                        />
                    </div>

                    {/* Company Logos - Two Slots */}
                    <div className={styles.field}>
                        <label className={styles.label}>
                            Company Logos
                            <span className={styles.hint}>(Transparent PNG Recommended)</span>
                        </label>

                        <div className={styles.logoGrid}>
                            {/* 1. Light Theme Logo (Colored/Dark) */}
                            <div className={styles.logoSlot}>
                                <span className={styles.slotLabel}>Light Mode (Colored)</span>
                                <div className={`${styles.logoPreview} ${styles.logoPreviewLight}`}>
                                    {logo?.base64 || logoOriginal ? (
                                        <img src={logo?.base64 || logoOriginal} alt="Light Mode Logo" className={styles.logoImage} />
                                    ) : (
                                        <div className={styles.logoPlaceholder}>
                                            <span className={styles.placeholderText}>No Logo</span>
                                        </div>
                                    )}
                                </div>
                                <div className={styles.slotControls}>
                                    <input
                                        type="file"
                                        accept="image/*"
                                        onChange={(e) => handleLogoUpload(e, 'original')}
                                        className={styles.fileInput}
                                        id="logo-original-upload"
                                    />
                                    <label htmlFor="logo-original-upload" className={styles.uploadBtnSmall}>
                                        {logo?.base64 ? 'Change' : 'Upload'}
                                    </label>
                                    {(logo?.base64 || logoOriginal) && (
                                        <button type="button" className={styles.removeLink} onClick={() => handleRemoveLogo('original')}>
                                            Remove
                                        </button>
                                    )}
                                </div>
                            </div>

                            {/* 2. Dark Theme Logo (White/Light) */}
                            <div className={styles.logoSlot}>
                                <span className={styles.slotLabel}>Dark Mode (White)</span>
                                <div className={`${styles.logoPreview} ${styles.logoPreviewDark}`}>
                                    {logo?.whiteLogo || logoWhite ? (
                                        <img src={logo?.whiteLogo || logoWhite} alt="Dark Mode Logo" className={styles.logoImage} />
                                    ) : (
                                        <div className={styles.logoPlaceholder}>
                                            <span className={styles.placeholderText}>No Logo</span>
                                        </div>
                                    )}
                                </div>
                                <div className={styles.slotControls}>
                                    <input
                                        type="file"
                                        accept="image/*"
                                        onChange={(e) => handleLogoUpload(e, 'white')}
                                        className={styles.fileInput}
                                        id="logo-white-upload"
                                    />
                                    <label htmlFor="logo-white-upload" className={styles.uploadBtnSmall}>
                                        {logo?.whiteLogo ? 'Change' : 'Upload'}
                                    </label>
                                    {(logo?.whiteLogo || logoWhite) && (
                                        <button type="button" className={styles.removeLink} onClick={() => handleRemoveLogo('white')}>
                                            Remove
                                        </button>
                                    )}
                                </div>
                            </div>
                        </div>

                        {logo && (
                            <div className={styles.detectedSpecs}>
                                <span className={styles.specItem}>✅ {logo.width}x{logo.height}px detected</span>
                                <span className={styles.specItem}>✅ Profile will be updated with these variants</span>
                            </div>
                        )}
                    </div>

                    {/* Messages */}
                    {error && (
                        <div className={styles.errorMessage}>{error}</div>
                    )}
                    {success && (
                        <div className={styles.successMessage}>{success}</div>
                    )}
                </div>

                {/* Actions */}
                <div className={styles.actions}>
                    {isModal ? (
                        <>
                            <button
                                type="button"
                                className={styles.skipBtn}
                                onClick={handleSkip}
                            >
                                Skip for Now
                            </button>
                            <button
                                type="button"
                                className={styles.saveBtn}
                                onClick={handleSave}
                                disabled={isProcessing}
                            >
                                Save & Continue
                            </button>
                        </>
                    ) : (
                        <>
                            <button
                                type="button"
                                className={styles.resetBtn}
                                onClick={handleReset}
                            >
                                Reset Profile
                            </button>
                            <button
                                type="button"
                                className={styles.saveBtn}
                                onClick={handleSave}
                                disabled={isProcessing}
                            >
                                Save Changes
                            </button>
                        </>
                    )}
                </div>
            </div>
        </div>
    );
}
