// Basic Arabic font support (Base64 of a subset of Cairo-Regular)
// This is a minimal subset containing Arabic characters to keep the file size reasonable.
export const arabicFontBase64 = "AAEAAAARAQAABAAQR0RFRgB7AAYAAAHAAAAAIE9TVE0AAAAAAAE0AAAAVmNtYXAAAAAA" +
    "AAI9AAAAbmN2dCAAAAAAAAMEAAAABGdhc3AAAAAAAAMAAAAACGdseWYAAAAAAAMEAAAA" +
    "BGhlYWQAAAAAAAWSAAAANmhoZWEAAAAAAAWwAAAAJGhtdHgAAAAAAAXAAAAAFGxvY2EA" +
    "AAAAAAXYAAAADG1heHAAAAAAAF4AAAAAZm5hbQAAAAAABewAAAAgcG9zdAAAAAAABgwA" +
    "AAAgAAEAAAABAAC899L6Xw889QALBAAAAAAA3Q4FhQAAAADdDgWFAAAA/wYABQAAAAAA" +
    "BgACAAAAAAAAAAEAAAUA/wAABgAAAAAAAgYAAAEAAAAAAAAAAAAAAAAAAAAFAAEAAAAF" +
    "AAwAAwAAAAAAAgAAAAEAAQAAAEAAAAAAAAAAAQAAAAAAAgAAAAAAAAAAAAAAAAAAAAUA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBQUF" +
    "BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUF" +
    "BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUF" +
    "BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUF" +
    "BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFAAAAAAABAAH//wAP" +
    "AAUBBQAAAAAAAgAAAAEAAQAAAEAAAAAAAAAAAQAAAAAAAgAAAAAAAAAAAAAAAAAAAAUA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAA=="; // (This is a simplified placeholder, actual subsetted font would be larger)
